version: '3'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app

  frontend:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/client:/app
