name: Fetch, process and merge data every hour

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  test_api_endpoints:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: |
          poetry install

      - name: Test API endpoints
        run: |
          poetry run python tests/test_station_api.py
          poetry run python tests/test_weather_api.py
          if [ $? -eq 0 ]; then
            echo "API tests executed successfully."
          else
            echo "Error testing API endpoints"
            exit 1
          fi

  fetch_station_data:
    needs: test_api_endpoints
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: |
          poetry install

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
        with:
          version: '3.48.4'

      - name: Setup Dagshub
        run: |
          poetry run dvc remote modify origin endpointurl https://dagshub.com/patrik.praprotnik/mBikePredictions.s3
          poetry run dvc remote modify origin --local access_key_id ${{ secrets.ACCESS_KEY_ID }}
          poetry run dvc remote modify origin --local secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Pull data
        run: |
          poetry run dvc pull -r origin

      - name: Unprotect
        run: |
          poetry run dvc unprotect data

      - name: Run fetch_station_data.py
        run: |
          poetry run python src/data/fetch_station_data.py
          if [ $? -eq 0 ]; then
            echo "fetch_station_data.py executed successfully."
          else
            echo "Error executing fetch_station_data.py"
            exit 1
          fi

      - name: Add data to DVC
        run: |
          poetry run dvc add data

      - name: DVC push
        run: |
          poetry run dvc push -r origin    

      - name: Push fetched station data to DagsHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update DVC data (fetch station data)

  preprocess_station_data:
    needs: fetch_station_data
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: |
          poetry install

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
        with:
          version: '3.48.4'

      - name: Setup Dagshub
        run: |
          poetry run dvc remote modify origin endpointurl https://dagshub.com/patrik.praprotnik/mBikePredictions.s3
          poetry run dvc remote modify origin --local access_key_id ${{ secrets.ACCESS_KEY_ID }}
          poetry run dvc remote modify origin --local secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Pull data
        run: |
          poetry run dvc pull -r origin

      - name: Unprotect
        run: |
          poetry run dvc unprotect data

      - name: Run preprocess_station_data.py
        run: |
          poetry run python src/data/preprocess_station_data.py
          if [ $? -eq 0 ]; then
            echo "preprocess_station_data.py executed successfully."
          else
            echo "Error executing preprocess_station_data.py"
            exit 1
          fi

      - name: Add data to DVC
        run: |
          poetry run dvc add data

      - name: DVC push
        run: |
          poetry run dvc push -r origin

      - name: Push preprocessed station data to DagsHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update DVC data (preprocess station data)

  fetch_weather_data:
    needs: preprocess_station_data
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'        

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: |
          poetry install

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
        with:
          version: '3.48.4'

      - name: Setup Dagshub
        run: |
          poetry run dvc remote modify origin endpointurl https://dagshub.com/patrik.praprotnik/mBikePredictions.s3
          poetry run dvc remote modify origin --local access_key_id ${{ secrets.ACCESS_KEY_ID }}
          poetry run dvc remote modify origin --local secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Pull data
        run: |
          poetry run dvc pull -r origin

      - name: Unprotect
        run: |
          poetry run dvc unprotect data

      - name: Run fetch_weather_data.py
        run: |
          poetry run python src/data/fetch_weather_data.py
          if [ $? -eq 0 ]; then
            echo "fetch_weather_data.py executed successfully."
          else
            echo "Error executing fetch_station_data.py"
            exit 1
          fi

      - name: Add data to DVC
        run: |
          poetry run dvc add data

      - name: DVC push
        run: |
          poetry run dvc push -r origin

      - name: Push fetched weather data to DagsHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update DVC data (fetch weather data)

  preprocess_weather_data:
    needs: fetch_weather_data
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: |
          poetry install

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
        with:
          version: '3.48.4'

      - name: Setup Dagshub
        run: |
          poetry run dvc remote modify origin endpointurl https://dagshub.com/patrik.praprotnik/mBikePredictions.s3
          poetry run dvc remote modify origin --local access_key_id ${{ secrets.ACCESS_KEY_ID }}
          poetry run dvc remote modify origin --local secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Pull data
        run: |
          poetry run dvc pull -r origin

      - name: Unprotect
        run: |
          poetry run dvc unprotect data

      - name: Run preprocess_weather_data.py
        run: |
          poetry run python src/data/preprocess_weather_data.py
          if [ $? -eq 0 ]; then
            echo "preprocess_weather_data.py executed successfully."
          else
            echo "Error executing preprocess_station_data.py"
            exit 1
          fi

      - name: Add data to DVC
        run: |
          poetry run dvc add data

      - name: DVC push
        run: |
          poetry run dvc push -r origin

      - name: Push preprocessed weather data to DagsHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update DVC data (preprocess weather data)

  merge_processed_data:
    needs: [preprocess_station_data, preprocess_weather_data]
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: |
          poetry install

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
        with:
          version: '3.48.4'

      - name: Setup Dagshub
        run: |
          poetry run dvc remote modify origin endpointurl https://dagshub.com/patrik.praprotnik/mBikePredictions.s3
          poetry run dvc remote modify origin --local access_key_id ${{ secrets.ACCESS_KEY_ID }}
          poetry run dvc remote modify origin --local secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Pull data
        run: |
          poetry run dvc pull -r origin

      - name: Unprotect
        run: |
          poetry run dvc unprotect data

      - name: Run merge_processed_data.py
        run: |
          poetry run python src/data/merge_processed_data.py
          if [ $? -eq 0 ]; then
            echo "merge_processed_data.py executed successfully."
          else
            echo "Error executing preprocess_station_data.py"
            exit 1
          fi

      - name: Add data to DVC
        run: |
          poetry run dvc add data

      - name: DVC push
        run: |
          poetry run dvc push -r origin

      - name: Push merged data to DagsHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update DVC data (merge processed data)

  validate_data:
    needs: merge_processed_data
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: |
          poetry install

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
        with:
          version: '3.48.4'

      - name: Setup Dagshub
        run: |
          poetry run dvc remote modify origin endpointurl https://dagshub.com/patrik.praprotnik/mBikePredictions.s3
          poetry run dvc remote modify origin --local access_key_id ${{ secrets.ACCESS_KEY_ID }}
          poetry run dvc remote modify origin --local secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Pull data
        run: |
          poetry run dvc pull -r origin

      - name: Unprotect
        run: |
          poetry run dvc unprotect data

      - name: Update current data
        run: |
          cp data/merged/station1_data.csv data/merged/current_data.csv

      - name: Validate data
        run: |
          poetry run python gx/run_mBikeCheckpoint.py
          if [ $? -eq 0 ]; then
            echo "run_mBikeCheckpoint.py executed successfully."
          else
            echo "Error executing run_mBikeCheckpoint.py"
            exit 1
          fi

      - name: Deploy validation output to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "gx/uncommitted/data_docs/local_site"
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Add data to DVC
        run: |
          poetry run dvc add data

      - name: DVC push
        run: |
          poetry run dvc push -r origin

      - name: Push merged data to DagsHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update DVC data (current data)

  test_data:
    needs: validate_data
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: |
          poetry install

      - name: Setup DVC
        uses: iterative/setup-dvc@v1
        with:
          version: '3.48.4'

      - name: Setup Dagshub
        run: |
          poetry run dvc remote modify origin endpointurl https://dagshub.com/patrik.praprotnik/mBikePredictions.s3
          poetry run dvc remote modify origin --local access_key_id ${{ secrets.ACCESS_KEY_ID }}
          poetry run dvc remote modify origin --local secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Pull data
        run: |
          poetry run dvc pull -r origin

      - name: Unprotect
        run: |
          poetry run dvc unprotect data

      - name: Update current data
        run: |
          cp data/merged/station1_data.csv data/merged/current_data.csv

      - name: Test data
        run: |
          poetry run python src/data/test_data.py
          if [ $? -eq 0 ]; then
            echo "test_data.py executed successfully."
          else
            echo "Error executing test_data.py"
            exit 1
          fi

      - name: Update reference data
        run: |
          cp data/merged/current_data.csv data/merged/reference_data.csv

      - name: Add data to DVC
        run: |
          poetry run dvc add data

      - name: DVC push
        run: |
          poetry run dvc push -r origin

      - name: Push merged data to DagsHub
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update DVC data (reference data)